version: '3'
services:
  mongodb:
    image: mongo:7.0.2-jammy
    container_name: my-mongodb
    restart: unless-stopped
    ports:
      - "27018:27018"
    volumes:
      - "./mongodb_data:/data/db"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    networks:
      - default

volumes:
  mongodb_data_dev:
