version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: my-mongodb
    ports:
      - "27017:27017"
    volumes:
      - "mongodb_data:/data/db"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin

  python-app:
    build: .
    container_name: my-python-app
    depends_on:
      - mongodb
    environment:
      MONGO_USERNAME: admin
      MONGO_PASSWORD: admin
      MONGO_HOST: mongodb
      MONGO_PORT: 27017

volumes:
  mongodb_data:
