version: '3'
services:
  mongodb:
    image: mongo:7.0.2-jammy
    container_name: my-mongodb
    ports:
      - "27017:27017"
    volumes:
      - "./mongodb_data:/data/db"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    networks:
      - default

  python-app:
    build: .
    container_name: my-python-app
    depends_on:
      - mongodb
    networks:
      - default

volumes:
  mongodb_data:
